"""empty message

Revision ID: 64b7420ce6d4
Revises: ce48cb8ee707
Create Date: 2024-07-26 13:15:43.838362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b7420ce6d4'
down_revision = 'ce48cb8ee707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_birth_year_key', type_='unique')
        batch_op.drop_constraint('character_eye_color_key', type_='unique')
        batch_op.drop_constraint('character_gender_key', type_='unique')
        batch_op.drop_constraint('character_hair_color_key', type_='unique')
        batch_op.drop_constraint('character_height_key', type_='unique')
        batch_op.drop_constraint('character_skin_color_key', type_='unique')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_climate_key', type_='unique')
        batch_op.drop_constraint('planet_diameter_key', type_='unique')
        batch_op.drop_constraint('planet_orbital_period_key', type_='unique')
        batch_op.drop_constraint('planet_population_key', type_='unique')
        batch_op.drop_constraint('planet_rotation_period_key', type_='unique')
        batch_op.drop_constraint('planet_terrain_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.create_unique_constraint('planet_terrain_key', ['terrain'])
        batch_op.create_unique_constraint('planet_rotation_period_key', ['rotation_period'])
        batch_op.create_unique_constraint('planet_population_key', ['population'])
        batch_op.create_unique_constraint('planet_orbital_period_key', ['orbital_period'])
        batch_op.create_unique_constraint('planet_diameter_key', ['diameter'])
        batch_op.create_unique_constraint('planet_climate_key', ['climate'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_skin_color_key', ['skin_color'])
        batch_op.create_unique_constraint('character_height_key', ['height'])
        batch_op.create_unique_constraint('character_hair_color_key', ['hair_color'])
        batch_op.create_unique_constraint('character_gender_key', ['gender'])
        batch_op.create_unique_constraint('character_eye_color_key', ['eye_color'])
        batch_op.create_unique_constraint('character_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
