"""empty message

Revision ID: ce48cb8ee707
Revises: 0d30b63881df
Create Date: 2024-07-24 20:11:30.888547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce48cb8ee707'
down_revision = '0d30b63881df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planet', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['id_planet'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_planet')

    # ### end Alembic commands ###
