"""empty message

Revision ID: f04a31155558
Revises: 936ec7d2b330
Create Date: 2024-07-24 18:29:43.909781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04a31155558'
down_revision = '936ec7d2b330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['height'])
        batch_op.create_unique_constraint(None, ['hair_color'])
        batch_op.create_unique_constraint(None, ['skin_color'])
        batch_op.create_unique_constraint(None, ['birth_year'])
        batch_op.drop_column('year_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_birth', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
